# Generated by Django 3.2 on 2022-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(max_length=70)),
                ('student_pass', models.CharField(max_length=30)),
            ],
        ),
    ]
